import type {BattleReport,Event,FireHeatmapResponse,GunneryAssistResponse,HexCoord,LegalAction,MovementPreview,MovementTrajectoriesResponse,Observation,Phase,ResearchConsent,Side,TorpedoAssistResponse,TorpedoTacticsResponse} from "./types";
export type {Side} from "./types";
// API 基址跟随 Vite base（部署到子路径 /tiedi 时构建带 --base=/tiedi/，自动落到
// /tiedi/api；默认 "/" 下与过去一致）。import.meta.env.BASE_URL 以 "/" 结尾。
const API = import.meta.env.BASE_URL.replace(/\/$/, "") + "/api";
const headers=(side?:Side):Record<string,string>=>{const value:Record<string,string>={"Content-Type":"application/json"};if(side)value["X-Player-Side"]=side;return value};
export interface LLMConnectionConfig{provider:"deepseek"|"zhipu";model:string;vision_enabled:boolean}
export interface SavedGameSummary{game_id:string;scenario_id:string;scenario_title:string;turn:number;max_turns:number;phase:string;mode:"hotseat"|"tutorial"|"vs_ai"|"llm";ai_profile:string|null;battle_report:boolean;realistic_command:boolean;command_delay_mode?:boolean;winner:Side|null;updated_at:string}
export interface ReplayCheckpoint{sequence:number;turn:number;phase:string;event_type:string|null;event_message:string|null}
export interface ImportedGame{game_id:string;source_game_id:string;scenario_id:string;scenario_title:string;turn:number;phase:string;mode:SavedGameSummary["mode"];ai_profile:string|null;battle_report:boolean;realistic_command:boolean;command_delay_mode?:boolean}
export interface ShipCatalogEntry{id:string;name:string;ship_type:string;displacement_band:string;vp:number;asset:string|null;class_name:string|null;complete:boolean}
export interface CustomShipDefinition{id:string;side:Side;position:string;heading:number;speed:number;asset:string}
export type RecommendedMode="pvp"|"pve"|null;
export interface CustomFormation{formation_id:string;name:string;ship_ids:string[];leader_id:string;flagship_id:string;reserve_flagship_id:string;spacing:1|2;heading:number}
export interface CustomScenarioDefinition{title:string;turns:number;visibility:{axis:number;allies:number};optional_rules:string[];ships:CustomShipDefinition[];formations:Record<Side,CustomFormation[]>;description?:string;recommended_mode?:RecommendedMode;map_columns?:number;map_rows?:number;printed_columns?:number|null;printed_rows?:number|null;id?:string}
export interface BuiltinScenarioTemplate extends CustomScenarioDefinition{warnings:string[]}
export async function shipCatalog():Promise<ShipCatalogEntry[]>{const r=await fetch(`${API}/ship-catalog`);if(!r.ok)throw new Error(await r.text());return r.json()}
export async function customScenarios():Promise<CustomScenarioDefinition[]>{const r=await fetch(`${API}/custom-scenarios`);if(!r.ok)throw new Error(await r.text());return r.json()}
export async function loadBuiltinScenarioTemplate(id:string):Promise<BuiltinScenarioTemplate>{const r=await fetch(`${API}/builtin-scenarios/${encodeURIComponent(id)}/template`);if(!r.ok)throw new Error(await r.text());return r.json()}
export async function createCustomScenario(body:CustomScenarioDefinition):Promise<CustomScenarioDefinition>{const r=await fetch(`${API}/custom-scenarios`,{method:"POST",headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function updateCustomScenario(id:string,body:CustomScenarioDefinition):Promise<CustomScenarioDefinition>{const r=await fetch(`${API}/custom-scenarios/${encodeURIComponent(id)}`,{method:"PUT",headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function deleteCustomScenario(id:string){const r=await fetch(`${API}/custom-scenarios/${encodeURIComponent(id)}`,{method:"DELETE",headers:headers()});if(!r.ok)throw new Error(await r.text())}
export async function realisticCommandRules():Promise<string>{const r=await fetch(`${API}/rules/realistic-command`);if(!r.ok)throw new Error(await r.text());return r.text()}
export async function commandDelayRules():Promise<string>{const r=await fetch(`${API}/rules/command-delay`);if(!r.ok)throw new Error(await r.text());return r.text()}
// 命令延迟模式的两种视图（只读）。舰队视图：只有被搭载编队是精确状态，其余以带年龄的
// 报告呈现；编队视图：该编队自身的本地视野，接触来自它自己的舰只。
export interface FormationReport{formation_id:string;name:string;side:Side;reported_turn:number|null;age_turns:number|null;link_status:string;authority:string;commander_ship_id:string|null;active_order_id:string|null;guide_position:{q:number;r:number}|null;guide_label:string|null;guide_heading:number|null;guide_speed:number|null;ship_count:number|null;geometry_kind:string|null;is_source_of_truth:boolean}
export interface FleetView{game_id:string;side:Side;turn:number;phase:Phase;embarked_formation_id:string|null;fleet_commander_ship_id:string|null;embarked:{formation_id?:string;name?:string;ship_ids?:string[];leader_id?:string;flagship_id?:string;spacing?:number;movement_style?:string;geometry_kind?:string;line_axis?:number|null;ships?:Array<Record<string,unknown>>;guide_trail?:string[]};reports:FormationReport[];contacts:Array<Record<string,unknown>>;messages:Array<Record<string,unknown>>;authority:Record<string,unknown>}
export interface FormationDecisionRecord{formation_id:string;turn:number;phase:Phase;selected_movement_action_id:string|null;selected_movement_plan:string|null;selected_contingency_branch:string|null;target_priority_adjustments:Array<{target_id:string|null;target_class:string|null;weight:number;reason:string}>;report_actions:string[];acknowledgement:boolean;rationale_summary:string;audit:Record<string,unknown>}
export interface FormationView{game_id:string;side:Side;formation_id:string;formation_name:string;turn:number;phase:Phase;authority:string;link_status:string;formation_state:Record<string,unknown>;local_contacts:Array<{ship_id:string;name:string;ship_type:string;position:string|null;range:number|null}>;active_mission_order:{order_id:string;mission:string;commander_intent:string;task_to_formation:string;coordination_measures:string[];roe:string[];loss_of_comm_plan:string[]} | null;received_messages:Array<{message_id:string;kind:string;status:string;issued_turn:number;delivered_turn:number|null}>;comm_state:Record<string,unknown>;stale_external_reports:FormationReport[];legal_formation_actions:Array<{action_id:string;plan:string;label:string;cost:number}>;legal_target_priority_options:Array<{target_id:string;target_class:string;range:number|null}>;report_actions:string[];local_priority_weight_limit:number}
export async function fleetView(id:string,side:Side):Promise<FleetView>{const r=await fetch(`${API}/games/${encodeURIComponent(id)}/command-delay/fleet-view`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function formationView(id:string,side:Side,formationId:string):Promise<FormationView>{const r=await fetch(`${API}/games/${encodeURIComponent(id)}/command-delay/formation-view/${encodeURIComponent(formationId)}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function createGame(scenario_id:string,seed:number,mode:"hotseat"|"tutorial"|"vs_ai"|"llm"="hotseat",aiProfile?:string,battleReport=true,llmApiKey?:string|null,researchConsent?:ResearchConsent|null,llmConfig?:LLMConnectionConfig|null,realisticCommand=false,tutorialScript?:"classic_night"|"erma_grand_fleet",commandDelayMode=false){const r=await fetch(`${API}/games`,{method:"POST",headers:headers(),body:JSON.stringify({scenario_id,seed,options:{mode,ai_profile:aiProfile??null,battle_report:battleReport,realistic_command:realisticCommand,command_delay_mode:commandDelayMode,tutorial_script:tutorialScript??null},llm_api_key:llmApiKey??null,llm_config:llmConfig??null,research_consent:researchConsent??{allow:false}})});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function savedGames():Promise<SavedGameSummary[]>{const r=await fetch(`${API}/games`);if(!r.ok)throw new Error(await r.text());return r.json()}
export async function importGame(bundle:unknown):Promise<ImportedGame>{const r=await fetch(`${API}/games/import`,{method:"POST",headers:headers(),body:JSON.stringify(bundle)});if(!r.ok)throw new Error(await r.text());return r.json()}
export function gameSaveUrl(id:string){return `${API}/games/${encodeURIComponent(id)}/save`}
export async function replayCheckpoints(id:string):Promise<ReplayCheckpoint[]>{const r=await fetch(`${API}/games/${encodeURIComponent(id)}/replay/checkpoints`);if(!r.ok)throw new Error(await r.text());return r.json()}
export async function replayView(id:string,side:Side,sequence:number):Promise<{checkpoint_sequence:number;view:Observation}>{const r=await fetch(`${API}/games/${encodeURIComponent(id)}/replay?sequence=${sequence}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function formationPreview(id:string,side:Side,formations:unknown[]){const r=await fetch(`${API}/games/${id}/formation-preview`,{method:"POST",headers:headers(side),body:JSON.stringify({formations})});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function formationMovementPreview(id:string,side:Side,formations:unknown[]){const r=await fetch(`${API}/games/${id}/formation-movement-preview`,{method:"POST",headers:headers(side),body:JSON.stringify({formations})});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function viewGame(id:string,side:Side,debug=false):Promise<Observation>{const r=await fetch(`${API}/games/${id}/view${debug?"?debug=true":""}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function sealedTrajectories(id:string,side:Side,debug=false){const r=await fetch(`${API}/games/${id}/sealed-trajectories${debug?"?debug=true":""}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<MovementTrajectoriesResponse>}
export async function legalActions(id:string,side:Side):Promise<LegalAction[]>{const r=await fetch(`${API}/games/${id}/legal-actions`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function advance(id:string,side:Side){const r=await fetch(`${API}/games/${id}/advance`,{method:"POST",headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<Event[]>}
export async function gameEvents(id:string,side:Side,after=0):Promise<Event[]>{const r=await fetch(`${API}/games/${id}/events?after=${after}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function submitOrders(id:string,side:Side,batch:unknown){const r=await fetch(`${API}/games/${id}/orders`,{method:"POST",headers:headers(side),body:JSON.stringify(batch)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<{valid:boolean;both_submitted:boolean;phase:string}>}
export async function suggestedOrders(id:string,side:Side,profile:string="balanced"){const r=await fetch(`${API}/games/${id}/suggested-orders?profile=${encodeURIComponent(profile)}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function movementPreview(id:string,side:Side,body:{ship_id:string;commands?:string[];plan?:string|null;hexes?:HexCoord[]}){const r=await fetch(`${API}/games/${id}/movement-preview`,{method:"POST",headers:headers(side),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<MovementPreview>}
export async function movementTrajectories(id:string,side:Side,plans:{ship_id:string;plan:string}[]){const r=await fetch(`${API}/games/${id}/movement-trajectories`,{method:"POST",headers:headers(side),body:JSON.stringify({plans})});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<MovementTrajectoriesResponse>}
export async function fieldOfFire(id:string,side:Side,shipId?:string|null):Promise<FireHeatmapResponse>{const r=await fetch(`${API}/games/${id}/field-of-fire`,{method:"POST",headers:headers(side),body:JSON.stringify({ship_id:shipId??null})});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function torpedoAssist(id:string,side:Side,body:{target_id?:string|null;launch?:Record<string,unknown>}){const r=await fetch(`${API}/games/${id}/torpedo-assist`,{method:"POST",headers:headers(side),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<TorpedoAssistResponse>}
export async function torpedoTactics(id:string,side:Side,profile="adaptive"){const r=await fetch(`${API}/games/${id}/torpedo-tactics?profile=${encodeURIComponent(profile)}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<TorpedoTacticsResponse>}
export async function gunneryAssist(id:string,side:Side,body:{assigned?:{ship_id:string;target_id:string}[]}){const r=await fetch(`${API}/games/${id}/gunnery-assist`,{method:"POST",headers:headers(side),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<GunneryAssistResponse>}
export async function tutorialOpponent(id:string,side:Side){const r=await fetch(`${API}/games/${id}/tutorial-opponent`,{method:"POST",headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function aiOpponent(id:string,side:Side,profile:string="balanced"){const r=await fetch(`${API}/games/${id}/ai-opponent`,{method:"POST",headers:headers(side),body:JSON.stringify({profile})});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function llmOpponent(id:string,side:Side,body:{timeout?:number;thinking_enabled?:boolean;api_key?:string;config?:LLMConnectionConfig}={}){const r=await fetch(`${API}/games/${id}/llm-opponent`,{method:"POST",headers:headers(side),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<{valid:boolean;ai_submitted:boolean;audits:{valid:boolean;elapsed_ms:number;validation_errors:string[];reasoning_preview:string|null}[]}>}
export async function battleReport(id:string):Promise<BattleReport>{const r=await fetch(`${API}/games/${id}/battle-report`);if(!r.ok)throw new Error(await r.text());return r.json()}
export function battleReportImageUrl(id:string,path:string){return `${API}/games/${id}/battle-report/image/${encodeURIComponent(path)}`}
export function battleReportDownloadUrl(id:string){return `${API}/games/${id}/battle-report.md`}
export async function handoff(id:string){await fetch(`${API}/games/${id}/handoff`,{method:"POST"})}
