import type {BattleReport,Event,FireHeatmapResponse,GunneryAssistResponse,HexCoord,LegalAction,MovementPreview,MovementTrajectoriesResponse,Observation,Side,TorpedoAssistResponse} from "./types";
// API 基址跟随 Vite base（部署到子路径 /tiedi 时构建带 --base=/tiedi/，自动落到
// /tiedi/api；默认 "/" 下与过去一致）。import.meta.env.BASE_URL 以 "/" 结尾。
const API = import.meta.env.BASE_URL.replace(/\/$/, "") + "/api";
const headers=(side?:Side):Record<string,string>=>{const value:Record<string,string>={"Content-Type":"application/json"};if(side)value["X-Player-Side"]=side;return value};
export async function createGame(scenario_id:string,seed:number,mode:"hotseat"|"tutorial"|"vs_ai"|"llm"="hotseat",aiProfile?:string,battleReport=true){const r=await fetch(`${API}/games`,{method:"POST",headers:headers(),body:JSON.stringify({scenario_id,seed,options:{mode,ai_profile:aiProfile??null,battle_report:battleReport}})});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function viewGame(id:string,side:Side,debug=false):Promise<Observation>{const r=await fetch(`${API}/games/${id}/view${debug?"?debug=true":""}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function sealedTrajectories(id:string,side:Side,debug=false){const r=await fetch(`${API}/games/${id}/sealed-trajectories${debug?"?debug=true":""}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<MovementTrajectoriesResponse>}
export async function legalActions(id:string,side:Side):Promise<LegalAction[]>{const r=await fetch(`${API}/games/${id}/legal-actions`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function advance(id:string,side:Side){const r=await fetch(`${API}/games/${id}/advance`,{method:"POST",headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<Event[]>}
export async function gameEvents(id:string,side:Side,after=0):Promise<Event[]>{const r=await fetch(`${API}/games/${id}/events?after=${after}`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function submitOrders(id:string,side:Side,batch:unknown){const r=await fetch(`${API}/games/${id}/orders`,{method:"POST",headers:headers(side),body:JSON.stringify(batch)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<{valid:boolean;both_submitted:boolean;phase:string}>}
export async function suggestedOrders(id:string,side:Side){const r=await fetch(`${API}/games/${id}/suggested-orders`,{headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function movementPreview(id:string,side:Side,body:{ship_id:string;commands?:string[];plan?:string|null;hexes?:HexCoord[]}){const r=await fetch(`${API}/games/${id}/movement-preview`,{method:"POST",headers:headers(side),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<MovementPreview>}
export async function movementTrajectories(id:string,side:Side,plans:{ship_id:string;plan:string}[]){const r=await fetch(`${API}/games/${id}/movement-trajectories`,{method:"POST",headers:headers(side),body:JSON.stringify({plans})});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<MovementTrajectoriesResponse>}
export async function fieldOfFire(id:string,side:Side,shipId?:string|null):Promise<FireHeatmapResponse>{const r=await fetch(`${API}/games/${id}/field-of-fire`,{method:"POST",headers:headers(side),body:JSON.stringify({ship_id:shipId??null})});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function torpedoAssist(id:string,side:Side,body:{target_id?:string|null;launch?:Record<string,unknown>}){const r=await fetch(`${API}/games/${id}/torpedo-assist`,{method:"POST",headers:headers(side),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<TorpedoAssistResponse>}
export async function gunneryAssist(id:string,side:Side,body:{assigned?:{ship_id:string;target_id:string}[]}){const r=await fetch(`${API}/games/${id}/gunnery-assist`,{method:"POST",headers:headers(side),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<GunneryAssistResponse>}
export async function tutorialOpponent(id:string,side:Side){const r=await fetch(`${API}/games/${id}/tutorial-opponent`,{method:"POST",headers:headers(side)});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function aiOpponent(id:string,side:Side,profile:string="balanced"){const r=await fetch(`${API}/games/${id}/ai-opponent`,{method:"POST",headers:headers(side),body:JSON.stringify({profile})});if(!r.ok)throw new Error(await r.text());return r.json()}
export async function llmOpponent(id:string,side:Side,body:{timeout?:number;thinking_enabled?:boolean}={}){const r=await fetch(`${API}/games/${id}/llm-opponent`,{method:"POST",headers:headers(side),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<{valid:boolean;ai_submitted:boolean;audits:{valid:boolean;elapsed_ms:number;validation_errors:string[];reasoning_preview:string|null}[]}>}
export async function battleReport(id:string):Promise<BattleReport>{const r=await fetch(`${API}/games/${id}/battle-report`);if(!r.ok)throw new Error(await r.text());return r.json()}
export function battleReportImageUrl(id:string,path:string){return `${API}/games/${id}/battle-report/image/${encodeURIComponent(path)}`}
export function battleReportDownloadUrl(id:string){return `${API}/games/${id}/battle-report.md`}
export async function handoff(id:string){await fetch(`${API}/games/${id}/handoff`,{method:"POST"})}
