import type {Marker,Ship,Side,TorpedoTrack} from "./types";
import {counterAssetUrl} from "./assets";
import {columnLabel,displayRowToAxial,headingRotation,headingVector,hexCenter,hexDistance,hexLabel,torpedoCounterRotation,HEX_SIZE} from "./hexGeometry";

const points=(cx:number,cy:number)=>Array.from({length:6},(_,i)=>{const a=Math.PI/180*(60*i);return `${cx+HEX_SIZE*Math.cos(a)},${cy+HEX_SIZE*Math.sin(a)}`}).join(" ");
const torpedoAsset=(track:TorpedoTrack)=>track.side==="axis"?`鱼雷${Math.min(3,track.salvo_size)}（日）.png`:`鱼雷${Math.min(2,track.salvo_size)}（美）.png`;

export function HexMap({ships,torpedoTracks,markers,onSelect,viewerSide,visibility,showVisibility=false}:{ships:Ship[];torpedoTracks:TorpedoTrack[];markers:Marker[];onSelect:(ship:Ship)=>void;viewerSide:Side;visibility:number;showVisibility?:boolean}){
 const observers=ships.filter(ship=>ship.side===viewerSide&&ship.position&&!ship.sunk).map(ship=>ship.position!);
 const hexes=[];for(let q=0;q<34;q++)for(let row=0;row<27;row++){const r=displayRowToAxial(q,row);const center=hexCenter(q,r);const observed=showVisibility&&observers.some(position=>hexDistance({q,r},position)<=visibility);hexes.push(<g key={`${q}:${r}`}><polygon className={observed?"in-visibility":undefined} points={points(center.x,center.y)}/><text x={center.x} y={center.y+3}>{columnLabel(q)}{row+1}</text></g>) }
 const directions=[1,2,3,4,5,6].map(heading=>({heading,tip:headingVector(heading,42),label:headingVector(heading,55)}));
 return <div className="map-frame"><svg viewBox="0 0 1280 1180" role="img" aria-label="A 至 HH、1 至 27 六角格战术地图"><defs><marker id="heading-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path fill="#f4d88c" d="M 0 0 L 10 5 L 0 10 z"/></marker></defs><g className="hexes">{hexes}</g>
  {torpedoTracks.map(track=>{const center=hexCenter(track.position.q,track.position.r);const vector=headingVector(track.heading,26);const launch=track.launch_position?hexLabel(track.launch_position):"旧存档未记录";const side=track.launch_side==="port"?"左舷":track.launch_side==="starboard"?"右舷":"舷侧未记录";const path=(track.traversed_hexes??[]).map(hexLabel).join(" → ");return <g className={`torpedo-counter ${track.side===viewerSide?"own":"observed"}`} key={track.id} transform={`translate(${center.x} ${center.y})`}><title>{track.side===viewerSide?"我方":"已发现敌方"}鱼雷 · {track.salvo_size} 枚 · {launch} → {hexLabel(track.position)} · {side}{track.launch_angle??""} · 航向 {track.heading} · 已走 {track.distance_travelled} 格 · 剩余射程 {track.range_remaining}{path?` · 航迹 ${path}`:""}</title><image href={counterAssetUrl(torpedoAsset(track))} x="-17" y="-17" width="34" height="34" transform={`rotate(${torpedoCounterRotation(track.heading)})`}/><line x1="0" y1="0" x2={vector.x} y2={vector.y} markerEnd="url(#heading-arrow)"/><text y="28">{track.salvo_size}枚</text></g>})}
  {ships.filter(ship=>ship.position).map(ship=>{const center=hexCenter(ship.position!.q,ship.position!.r);if(ship.sunk)return <g className="status-counter sunk" key={ship.id} transform={`translate(${center.x} ${center.y})`} onClick={()=>onSelect(ship)}><title>{ship.name} · 沉没中</title><image href={counterAssetUrl("沉没中.png")} x="-22" y="-22" width="44" height="44"/><text y="31">{ship.name}</text></g>;const rotation=headingRotation(ship.heading);return <g className={`counter ${ship.side}`} key={ship.id} transform={`translate(${center.x} ${center.y}) rotate(${rotation})`} onClick={()=>onSelect(ship)}><title>{ship.name} · 舰首 {ship.heading}</title>{ship.asset&&<image href={counterAssetUrl(ship.asset)} x="-22" y="-14" width="44" height="28" preserveAspectRatio="xMidYMid meet"/>}<path className="bow-pointer" d="M -25 0 L -17 -5 L -17 5 Z"/>{ship.fire_markers>0&&<g className="fire-marker" transform={`rotate(${-rotation}) translate(18 -17)`}><image href={counterAssetUrl("起火.png")} x="-11" y="-11" width="22" height="22"/><text x="8" y="-7">×{ship.fire_markers}</text></g>}<text transform={`rotate(${-rotation})`} y="30">{ship.name}</text></g>})}
  {markers.filter(marker=>marker.position&&!['fire','sunk'].includes(marker.kind)).map(marker=>{const center=hexCenter(marker.position!.q,marker.position!.r);return <circle className={`map-marker ${marker.kind}`} key={marker.id} cx={center.x} cy={center.y} r="7"><title>{marker.kind}</title></circle>})}
  <g className="heading-compass" transform="translate(82 1088)" aria-label="舰首方向：1右上、2右下、3下、4左下、5左上、6上"><rect x="-70" y="-70" width="140" height="150" rx="8"/><text className="compass-title" x="0" y="72">舰首方向</text>{directions.map(({heading,tip,label})=><g key={heading}><line x1="0" y1="0" x2={tip.x} y2={tip.y} markerEnd="url(#heading-arrow)"/><text x={label.x} y={label.y+3}>{heading}</text></g>)}<circle r="5"/></g></svg></div>;
}
