import type {Ship,Side} from "./types";
import {counterAssetUrl} from "./assets";
import {columnLabel,displayRowToAxial,headingRotation,headingVector,hexCenter,hexDistance,HEX_SIZE} from "./hexGeometry";
const points=(cx:number,cy:number)=>Array.from({length:6},(_,i)=>{const a=Math.PI/180*(60*i);return `${cx+HEX_SIZE*Math.cos(a)},${cy+HEX_SIZE*Math.sin(a)}`}).join(" ");
export function HexMap({ships,onSelect,viewerSide,visibility,showVisibility=false}:{ships:Ship[];onSelect:(ship:Ship)=>void;viewerSide:Side;visibility:number;showVisibility?:boolean}){
 const observers=ships.filter(ship=>ship.side===viewerSide&&ship.position&&!ship.sunk).map(ship=>ship.position!);
 const hexes=[];for(let q=0;q<34;q++)for(let row=0;row<27;row++){const r=displayRowToAxial(q,row);const center=hexCenter(q,r);const observed=showVisibility&&observers.some(position=>hexDistance({q,r},position)<=visibility);hexes.push(<g key={`${q}:${r}`}><polygon className={observed?"in-visibility":undefined} points={points(center.x,center.y)}/><text x={center.x} y={center.y+3}>{columnLabel(q)}{row+1}</text></g>) }
 const directions=[1,2,3,4,5,6].map(heading=>({heading,tip:headingVector(heading,42),label:headingVector(heading,55)}));
 return <div className="map-frame"><svg viewBox="0 0 1280 1180" role="img" aria-label="A 至 HH、1 至 27 六角格战术地图"><defs><marker id="heading-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path fill="#f4d88c" d="M 0 0 L 10 5 L 0 10 z"/></marker></defs><g className="hexes">{hexes}</g>{ships.filter(s=>s.position&&!s.sunk).map(s=>{const p=s.position!;const center=hexCenter(p.q,p.r);const rotation=headingRotation(s.heading);return <g className={`counter ${s.side}`} key={s.id} transform={`translate(${center.x} ${center.y}) rotate(${rotation})`} onClick={()=>onSelect(s)}><title>{s.name} · 舰首 {s.heading}</title>{s.asset&&<image href={counterAssetUrl(s.asset)} x="-22" y="-14" width="44" height="28" preserveAspectRatio="xMidYMid meet"/>}<path className="bow-pointer" d="M -25 0 L -17 -5 L -17 5 Z"/><text transform={`rotate(${-rotation})`} y="30">{s.name}</text></g>})}<g className="heading-compass" transform="translate(82 1088)" aria-label="舰首方向：1右上、2右下、3下、4左下、5左上、6上"><rect x="-70" y="-70" width="140" height="150" rx="8"/><text className="compass-title" x="0" y="72">舰首方向</text>{directions.map(({heading,tip,label})=><g key={heading}><line x1="0" y1="0" x2={tip.x} y2={tip.y} markerEnd="url(#heading-arrow)"/><text x={label.x} y={label.y+3}>{heading}</text></g>)}<circle r="5"/></g></svg></div>
}
