import {useMemo} from "react";
import type {HexCoord,Observation,Ship,Side} from "./types";

type MovementPlan={ship_id:string;plan:string;speed?:number|null};
type ContactMove={marker_id:string;plan:string};
type Reinforcement={ship_id:string;entry_hex:HexCoord;heading:number;speed:number};
type ContactSetup={marker_id:string;entry_hex:HexCoord;heading:number;speed:4|5;ship_ids:string[]};
type TorpedoPlan={ship_id:string;launcher_id:string|null;count:number;speed:string;launch_at_mf:number;launch_hex:HexCoord|null;bearing:number|null;launch_side:"port"|"starboard"|null;launch_angle:"A"|"B"|"X"|"Y"|null;setting_index:number};
type MountPlan={mount_id:string;target_id:string};
type GunneryPlan={ship_id:string;primary_target:string|null;secondary_target:string|null;searchlight_target:string|null;mounts:MountPlan[]};
type PlanBatch={side:Side;phase:string;movement:MovementPlan[];contact_movement:ContactMove[];reinforcements:Reinforcement[];contacts:ContactSetup[];torpedoes:TorpedoPlan[];gunnery:GunneryPlan[];smoke_ships:string[];smoke:unknown[];illumination:unknown[];searchlights:unknown[];confirmation:{ready:boolean}};

const numberValue=(value:string)=>Number.parseInt(value,10)||0;

export function PlanSheet({view,side,draft,setDraft,intent,setIntent,tutorial=false}:{view:Observation;side:Side;draft:string;setDraft:(value:string)=>void;intent:string;setIntent:(value:string)=>void;tutorial?:boolean}){
 const parsed=useMemo(()=>{try{return JSON.parse(draft) as PlanBatch}catch{return null}},[draft]);
 const own=view.ships.filter(ship=>ship.side===side&&!ship.sunk);
 const enemies=view.ships.filter(ship=>ship.side!==side&&!ship.sunk&&ship.position);
 const shipName=(id:string)=>view.ships.find(ship=>ship.id===id)?.name??id;
 const commit=(change:(next:PlanBatch)=>void)=>{if(!parsed)return;const next=structuredClone(parsed);change(next);setDraft(JSON.stringify(next,null,2))};
 const setCoord=(coord:HexCoord,key:"q"|"r",value:string)=>{coord[key]=numberValue(value)};
 const addTorpedo=()=>commit(next=>{const ship=own.find(item=>item.position&&item.torpedo_launchers.some(launcher=>!launcher.destroyed&&launcher.loaded>0));if(!ship)return;const launcher=ship.torpedo_launchers.find(item=>!item.destroyed&&item.loaded>0)!;const launchSide=launcher.arcs.includes("port")?"port":"starboard";next.torpedoes.push({ship_id:ship.id,launcher_id:launcher.id,count:1,speed:"fast",launch_at_mf:1,launch_hex:ship.position,bearing:ship.heading,launch_side:launchSide,launch_angle:launchSide==="port"?"A":"X",setting_index:0})});
 const addGunnery=()=>commit(next=>{const ship=own.find(item=>item.position&&item.gun_mounts.some(mount=>!mount.destroyed&&!mount.fired_this_phase));const target=enemies[0];if(!ship||!target)return;next.gunnery.push({ship_id:ship.id,primary_target:target.id,secondary_target:null,searchlight_target:null,mounts:ship.gun_mounts.filter(mount=>!mount.destroyed&&!mount.fired_this_phase).map(mount=>({mount_id:mount.id,target_id:target.id}))})});
 const fillTutorialMovement=()=>commit(next=>{next.movement.forEach((order,index)=>{order.plan=index===0?"1":"0";order.speed=null})});
 if(!draft)return <section className="plan-sheet"><p className="empty-plan">正在载入本阶段合法订单……</p></section>;
 if(!parsed)return <section className="plan-sheet"><p className="form-error">高级 JSON 格式错误；修正后才能继续使用计划表。</p><details open><summary>高级 JSON</summary><textarea aria-label="本阶段秘密订单 JSON" value={draft} onChange={event=>setDraft(event.target.value)} spellCheck={false}/></details></section>;
 return <section className="plan-sheet">
  {tutorial&&<div className="field-coach">
   <b>现在照着做</b>
   {view.phase==="reinforcement"&&<ol><li>确认下方显示“本阶段没有可用增援”。</li><li>不需要填写坐标。</li><li>点击页面右上角的确认按钮。</li></ol>}
   {view.phase==="movement_planning"&&<><ol><li>先点地图上的一艘德舰，查看“上回合实际消耗”和“本回合合法消耗”。淡色海格是己舰当前 {view.visibility} 格视距覆盖。</li><li>最大速度不是必须耗尽；想定 3 的 DD 从 5 MF 最多减 5，所以可合法填写 0。</li><li>本课用卡尔直航 1 MF、另两舰停船来保持与英舰接触，便于下一课学习炮击。</li></ol><button type="button" onClick={fillTutorialMovement}>填入保持接触示例（1 / 0 / 0）</button></>}
   {view.phase==="torpedo_planning"&&<ol><li>鱼雷是可选命令；第一次学习建议保持空表。</li><li>若添加发射，“发射 MF”不能超过该舰上一阶段计划的航行 MF。</li><li>误加时点“删除”，空表也可合法提交。</li></ol>}
   {view.phase==="gunnery"&&<ol><li>先看地图上是否有已观察敌舰。</li><li>点“添加齐射”，再选目标并勾选可用炮位。</li><li>没有目标或射界时保持空表，直接提交。</li></ol>}
  </div>}
  <label className="intent">指挥意图 / 备忘<textarea value={intent} onChange={event=>setIntent(event.target.value)} placeholder="例如：保持队形向西北航行，避免在本回合过早暴露。"/></label>
  {view.phase==="reinforcement"&&<div><h3>增援计划</h3>{parsed.reinforcements.length===0?<p className="empty-plan">本阶段没有可用增援，提交即确认。</p>:parsed.reinforcements.map((order,index)=><div className="plan-row" key={order.ship_id}><b>{shipName(order.ship_id)}</b><label>入口 q<input type="number" value={order.entry_hex.q} onChange={event=>commit(next=>setCoord(next.reinforcements[index].entry_hex,"q",event.target.value))}/></label><label>入口 r<input type="number" value={order.entry_hex.r} onChange={event=>commit(next=>setCoord(next.reinforcements[index].entry_hex,"r",event.target.value))}/></label><label>舰首<select value={order.heading} onChange={event=>commit(next=>next.reinforcements[index].heading=numberValue(event.target.value))}>{[1,2,3,4,5,6].map(value=><option key={value}>{value}</option>)}</select></label><label>速度<input type="number" min="0" value={order.speed} onChange={event=>commit(next=>next.reinforcements[index].speed=numberValue(event.target.value))}/></label></div>)}</div>}
  {view.phase==="contact_setup"&&<div><h3>隐蔽接触部署</h3>{parsed.contacts.map((order,index)=><div className="plan-row" key={order.marker_id}><b>{order.marker_id}</b><label>入口 q<input type="number" value={order.entry_hex.q} onChange={event=>commit(next=>setCoord(next.contacts[index].entry_hex,"q",event.target.value))}/></label><label>入口 r<input type="number" value={order.entry_hex.r} onChange={event=>commit(next=>setCoord(next.contacts[index].entry_hex,"r",event.target.value))}/></label><label>舰首<select value={order.heading} onChange={event=>commit(next=>next.contacts[index].heading=numberValue(event.target.value))}>{[1,2,3,4,5,6].map(value=><option key={value}>{value}</option>)}</select></label><label>速度<select value={order.speed} onChange={event=>commit(next=>next.contacts[index].speed=numberValue(event.target.value) as 4|5)}><option>4</option><option>5</option></select></label><small>{order.ship_ids.length?order.ship_ids.map(shipName).join("、"):"诱饵"}</small></div>)}</div>}
  {view.phase==="movement_planning"&&<div><h3>逐舰移动计划</h3><p className="notation-help">数字表示直航 MF；P/S 表示左/右转 60°，PP/SS 表示 120°。例如 <code>3PP2</code>。</p>{parsed.movement.map((order,index)=>{const ship=own.find(item=>item.id===order.ship_id);return <div className="plan-row movement" key={order.ship_id}><b>{shipName(order.ship_id)}</b><label>航路<input value={order.plan} onChange={event=>commit(next=>next.movement[index].plan=event.target.value.toUpperCase())}/></label><label>声明速度<input type="number" min={ship?.min_legal_speed??0} max={ship?.max_legal_speed??undefined} value={order.speed??""} placeholder="由航路计算" onChange={event=>commit(next=>next.movement[index].speed=event.target.value===""?null:numberValue(event.target.value))}/></label><small>上回合 {ship?.current_speed} MF · 本回合合法 {ship?.min_legal_speed??"?"}–{ship?.max_legal_speed??"?"} MF · 循环上限 {ship?.max_speed??"?"}</small></div>})}{parsed.contact_movement.map((order,index)=><div className="plan-row movement" key={order.marker_id}><b>{order.marker_id}</b><label>接触航路<input value={order.plan} onChange={event=>commit(next=>next.contact_movement[index].plan=event.target.value.toUpperCase())}/></label></div>)}</div>}
  {view.phase==="torpedo_planning"&&<div><div className="plan-heading"><h3>鱼雷计划</h3><button type="button" onClick={addTorpedo}>＋ 添加发射</button></div>{parsed.torpedoes.length===0&&<p className="empty-plan success-note">✓ 空表是合法命令：本阶段不发射鱼雷。</p>}{parsed.torpedoes.map((order,index)=><div className="plan-row torpedo" key={`${order.ship_id}-${index}`}><b>{shipName(order.ship_id)}</b><label>① 发射器<select value={order.launcher_id??""} onChange={event=>commit(next=>next.torpedoes[index].launcher_id=event.target.value)}>{own.find(ship=>ship.id===order.ship_id)?.torpedo_launchers.map(launcher=><option key={launcher.id} value={launcher.id}>{launcher.id}（{launcher.loaded} 枚）</option>)}</select></label><label>② 枚数<input type="number" min="1" max="9" value={order.count} onChange={event=>commit(next=>next.torpedoes[index].count=numberValue(event.target.value))}/></label><label>③ 发射 MF<input type="number" min="1" max="8" value={order.launch_at_mf} onChange={event=>commit(next=>next.torpedoes[index].launch_at_mf=numberValue(event.target.value))}/></label><label>④ 舷侧<select value={order.launch_side??""} onChange={event=>commit(next=>next.torpedoes[index].launch_side=event.target.value as "port"|"starboard")}><option value="port">左舷</option><option value="starboard">右舷</option></select></label><label>⑤ 发射角<select value={order.launch_angle??""} onChange={event=>commit(next=>next.torpedoes[index].launch_angle=event.target.value as "A"|"B"|"X"|"Y")}><option>A</option><option>B</option><option>X</option><option>Y</option></select></label><button type="button" className="danger" onClick={()=>commit(next=>next.torpedoes.splice(index,1))}>删除这次发射</button></div>)}</div>}
  {view.phase==="gunnery"&&<div><div className="plan-heading"><h3>炮击计划</h3><button type="button" onClick={addGunnery}>＋ 添加齐射</button></div>{parsed.gunnery.length===0&&<p className="empty-plan">尚未安排炮击。</p>}{parsed.gunnery.map((order,index)=>{const ship=own.find(item=>item.id===order.ship_id);return <div className="plan-row gunnery" key={`${order.ship_id}-${index}`}><b>{shipName(order.ship_id)}</b><label>主目标<select value={order.primary_target??""} onChange={event=>commit(next=>{const target=event.target.value;next.gunnery[index].primary_target=target;next.gunnery[index].mounts.forEach(mount=>mount.target_id=target)})}>{enemies.map(target=><option key={target.id} value={target.id}>{target.name}</option>)}</select></label><fieldset><legend>炮位</legend>{ship?.gun_mounts.map(mount=>{const checked=order.mounts.some(item=>item.mount_id===mount.id);return <label key={mount.id}><input type="checkbox" checked={checked} disabled={mount.destroyed||mount.fired_this_phase} onChange={event=>commit(next=>{const mounts=next.gunnery[index].mounts;if(event.target.checked)mounts.push({mount_id:mount.id,target_id:next.gunnery[index].primary_target??""});else next.gunnery[index].mounts=mounts.filter(item=>item.mount_id!==mount.id)})}/>{mount.id} · GF {mount.firepower}</label>})}</fieldset><button type="button" className="danger" onClick={()=>commit(next=>next.gunnery.splice(index,1))}>删除</button></div>})}<fieldset className="smoke-options"><legend>施放烟幕（仅规则 9.7 开启时合法）</legend>{own.filter(ship=>["DD","CL"].includes(ship.ship_type)).map(ship=><label key={ship.id}><input type="checkbox" checked={parsed.smoke_ships.includes(ship.id)} onChange={event=>commit(next=>{next.smoke_ships=event.target.checked?[...next.smoke_ships,ship.id]:next.smoke_ships.filter(id=>id!==ship.id)})}/>{ship.name}</label>)}</fieldset></div>}
  <details className="advanced-json"><summary>高级 JSON / 完整审计订单</summary><p>照明弹、探照灯及特殊命令可在此精确编辑。</p><textarea aria-label="本阶段秘密订单 JSON" value={draft} onChange={event=>setDraft(event.target.value)} spellCheck={false}/></details>
 </section>;
}
